// Prints the Neural Arena bot circuit (sdk/src/neuro/arena.ts) for tapeout().
//
//   node scripts/arena-netlist.ts           # JSON: { hex, nIn, nOut, nand, bytes, neurons }
//   node scripts/arena-netlist.ts --hex     # the netlist hex only (for cast send)
//   node scripts/arena-netlist.ts --sol     # (re)write test/arena/ArenaBotNetlist.sol for Foundry
//
// Read-only: no RPC, no keys.

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { parseArgs } from 'node:util';
import { getArenaCircuit } from '../src/neuro/arena.ts';

const { values: args } = parseArgs({ options: { hex: { type: 'boolean', default: false }, sol: { type: 'boolean', default: false } } });
const a = getArenaCircuit();

if (args.sol) {
  const path = fileURLToPath(new URL('../../test/arena/ArenaBotNetlist.sol', import.meta.url));
  const body = `// SPDX-License-Identifier: MIT
pragma solidity 0.8.28;

/// @notice The Neural Arena bot circuit, generated by sdk/scripts/arena-netlist.ts --sol.
/// @dev Do not edit by hand: sdk/test/arena.test.ts checks this constant against the SDK build.
library ArenaBotNetlist {
    uint32 internal constant N_IN = ${a.nIn};
    uint32 internal constant N_OUT = ${a.nOut};
    uint256 internal constant NAND_COUNT = ${a.nand};
    bytes internal constant NETLIST =
        hex"${a.hex.slice(2)}";
}
`;
  writeFileSync(path, body);
  console.log(`wrote ${path} (${a.nand} NAND, ${(a.hex.length - 2) / 2} bytes)`);
} else if (args.hex) {
  console.log(a.hex);
} else {
  console.log(JSON.stringify({ hex: a.hex, nIn: a.nIn, nOut: a.nOut, nand: a.nand, bytes: (a.hex.length - 2) / 2, neurons: a.neurons }, null, 2));
}
