// AUTO-GENERATED by scripts/gen-abi.mjs from CerebrLens.sol/CerebrLens.json. Do not edit.
export const cerebrLensAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "processor",
        "type": "address",
        "internalType": "contract CerebrProcessor"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "CIRCUIT",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract CerebrCircuit"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MAX_CURVE_POINTS",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "PROCESSOR",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract CerebrProcessor"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "circuitView",
    "inputs": [
      {
        "name": "id",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "v",
        "type": "tuple",
        "internalType": "struct CerebrLens.CircuitView",
        "components": [
          {
            "name": "id",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "tier",
            "type": "uint8",
            "internalType": "enum Tier"
          },
          {
            "name": "revealed",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "commitBlock",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "revealReadyBlock",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "seed",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "traits",
            "type": "tuple",
            "internalType": "struct CerebrCircuit.Traits",
            "components": [
              {
                "name": "tier",
                "type": "uint8",
                "internalType": "enum Tier"
              },
              {
                "name": "revealed",
                "type": "bool",
                "internalType": "bool"
              },
              {
                "name": "architecture",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "cores",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "clockTenthsGHz",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "nodeNm",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "rarity",
                "type": "string",
                "internalType": "string"
              }
            ]
          },
          {
            "name": "tba",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "tbaDeployed",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "tbaBalance",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "fusedInto",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "curvePoints",
    "inputs": [
      {
        "name": "n",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "supplies",
        "type": "uint256[]",
        "internalType": "uint256[]"
      },
      {
        "name": "prices",
        "type": "uint256[]",
        "internalType": "uint256[]"
      },
      {
        "name": "currentSupply",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "currentPrice",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "protocolState",
    "inputs": [],
    "outputs": [
      {
        "name": "st",
        "type": "tuple",
        "internalType": "struct CerebrLens.ProtocolState",
        "components": [
          {
            "name": "blockNumber",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "totalSupply",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "maxSupply",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "currentPrice",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "basePrice",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "slope",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "balance",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "reserveRequired",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "protocolFees",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "surplusReserve",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "totalCbrBurned",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "totalCircuits",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "mintedByTier",
            "type": "uint256[4]",
            "internalType": "uint256[4]"
          },
          {
            "name": "tapeOutCosts",
            "type": "uint256[3]",
            "internalType": "uint256[3]"
          },
          {
            "name": "sellFeeBps",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "paused",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "launchActive",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "launchEndBlock",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "walletCapPerBlock",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "blockCap",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "processor",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "circuit",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "erc6551Registry",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "accountImplementation",
            "type": "address",
            "internalType": "address"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "quoteBuy",
    "inputs": [
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "quoteBuyExactOKB",
    "inputs": [
      {
        "name": "okbIn",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "cost",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "quoteSell",
    "inputs": [
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "gross",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "fee",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "net",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "userState",
    "inputs": [
      {
        "name": "user",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "u",
        "type": "tuple",
        "internalType": "struct CerebrLens.UserState",
        "components": [
          {
            "name": "user",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "cbrBalance",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "okbBalance",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "launchWalletRemaining",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "launchBlockRemaining",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "circuits",
            "type": "tuple[]",
            "internalType": "struct CerebrLens.CircuitView[]",
            "components": [
              {
                "name": "id",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "tier",
                "type": "uint8",
                "internalType": "enum Tier"
              },
              {
                "name": "revealed",
                "type": "bool",
                "internalType": "bool"
              },
              {
                "name": "commitBlock",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "revealReadyBlock",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "seed",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "traits",
                "type": "tuple",
                "internalType": "struct CerebrCircuit.Traits",
                "components": [
                  {
                    "name": "tier",
                    "type": "uint8",
                    "internalType": "enum Tier"
                  },
                  {
                    "name": "revealed",
                    "type": "bool",
                    "internalType": "bool"
                  },
                  {
                    "name": "architecture",
                    "type": "string",
                    "internalType": "string"
                  },
                  {
                    "name": "cores",
                    "type": "uint256",
                    "internalType": "uint256"
                  },
                  {
                    "name": "clockTenthsGHz",
                    "type": "uint256",
                    "internalType": "uint256"
                  },
                  {
                    "name": "nodeNm",
                    "type": "uint256",
                    "internalType": "uint256"
                  },
                  {
                    "name": "rarity",
                    "type": "string",
                    "internalType": "string"
                  }
                ]
              },
              {
                "name": "tba",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "tbaDeployed",
                "type": "bool",
                "internalType": "bool"
              },
              {
                "name": "tbaBalance",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "fusedInto",
                "type": "uint256",
                "internalType": "uint256"
              }
            ]
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "error",
    "name": "InvalidPointCount",
    "inputs": []
  }
] as const
