#!/usr/bin/env node
// Generates typed ABI modules (src/abi/*.ts, `as const` for viem/wagmi inference) from forge artifacts.
// Usage: node scripts/gen-abi.mjs [forgeOutDir]   (default: ../out, or $FORGE_OUT)
// Build first: (cd .. && forge build)  or  forge build --out out-xyz  then pass that dir.
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const appRoot = resolve(here, '..')
const outDir = resolve(appRoot, process.argv[2] ?? process.env.FORGE_OUT ?? '../out')
const abiDir = join(appRoot, 'src/abi')

// [artifact file, contract name, exported const name]
const contracts = [
  ['CerebrProcessor.sol', 'CerebrProcessor', 'cerebrProcessorAbi'],
  ['CerebrCircuit.sol', 'CerebrCircuit', 'cerebrCircuitAbi'],
  ['CerebrLens.sol', 'CerebrLens', 'cerebrLensAbi'],
  ['ERC6551Registry.sol', 'ERC6551Registry', 'erc6551RegistryAbi'],
  ['CerebrAccount.sol', 'CerebrAccount', 'cerebrAccountAbi'],
]

mkdirSync(abiDir, { recursive: true })
const exports = []
for (const [file, name, constName] of contracts) {
  const path = join(outDir, file, `${name}.json`)
  if (!existsSync(path)) {
    console.error(`missing artifact ${path} - run forge build first`)
    process.exit(1)
  }
  const { abi } = JSON.parse(readFileSync(path, 'utf8'))
  const body =
    `// AUTO-GENERATED by scripts/gen-abi.mjs from ${file}/${name}.json. Do not edit.\n` +
    `export const ${constName} = ${JSON.stringify(abi, null, 2)} as const\n`
  writeFileSync(join(abiDir, `${name}.ts`), body)
  exports.push(`export { ${constName} } from './${name}.ts'`)
  console.log(`abi: ${name} (${abi.length} entries)`)
}
writeFileSync(join(abiDir, 'index.ts'), `// AUTO-GENERATED by scripts/gen-abi.mjs. Do not edit.\n${exports.join('\n')}\n`)
