#!/usr/bin/env node
// Collects the Cerebr CPU launch records (../launch/out/*.json, written by the launch script) into
// src/generated/cpus.ts. Usage: node scripts/sync-cpu.mjs [launchOutDir] [outFile]
//
// Primary input: the launch script's record (schema "cerebr.launch/1", see LAUNCH.md):
//   { "network": "xlayer" | "fork", "chainId": 196, "processor": { "circuits", "transistors", "createBlock" },
//     "scope": "0x.." (optional), "circuits": [{ "key": "xor-net", "circuitId": "3" }, ...] }
// Also accepted (extra fields are ignored):
//   {
//     "chainId": 196,                       // or the file name: 196.json
//     "fork": false,                        // true (or a file named fork*.json / *-fork.json / *.fork.json)
//                                           //   -> the local X Layer fork, chain 31337 in the app
//     "cpu": { "circuits": "0x..", "transistors": "0x..", "block": 123 },
//                                           //   (or "circuits" / "transistors" at the top level)
//     "scope": "0x..",                      // CerebrScope, optional (also "cerebrScope")
//     "catalog": { "xor-net": 3 }           // catalog id -> circuit id, optional (also "tapeouts":
//                                           //   [{ "id": "xor-net", "circuitId": 3 }], or "circuits" as a map)
//   }
// Dry runs (*.dry-run.json) are skipped.
import { readdirSync, readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs'
import { dirname, join, resolve, relative } from 'node:path'
import { fileURLToPath } from 'node:url'

const FORK_CHAIN_ID = 31337
const here = dirname(fileURLToPath(import.meta.url))
const appRoot = resolve(here, '..')
const dir = resolve(appRoot, process.argv[2] ?? '../launch/out')
const out = resolve(appRoot, process.argv[3] ?? 'src/generated/cpus.ts')

const isAddr = (v) => typeof v === 'string' && /^0x[0-9a-fA-F]{40}$/.test(v)
const cpus = {}

function catalogOf(j) {
  const map = {}
  const add = (k, v) => {
    if (typeof k === 'string' && v !== undefined && v !== null && /^\d+$/.test(String(v))) map[k] = String(v)
  }
  for (const src of [j.catalog, typeof j.circuits === 'object' && !Array.isArray(j.circuits) ? j.circuits : undefined]) {
    if (src && typeof src === 'object') for (const [k, v] of Object.entries(src)) add(k, typeof v === 'object' ? v?.circuitId ?? v?.id : v)
  }
  for (const t of Array.isArray(j.tapeouts) ? j.tapeouts : []) add(t.id ?? t.catalogId ?? t.name, t.circuitId)
  // cerebr.launch/1: circuits[] = [{ key, circuitId, ... }]
  for (const c of Array.isArray(j.circuits) ? j.circuits : []) add(c.key, c.circuitId)
  return map
}

if (existsSync(dir)) {
  for (const f of readdirSync(dir).sort()) {
    if (!f.endsWith('.json') || f.endsWith('.dry-run.json')) continue
    const j = JSON.parse(readFileSync(join(dir, f), 'utf8'))
    const fork = j.fork === true || j.network === 'fork' || /(^fork|[-.]fork\.json$)/.test(f)
    const chainId = fork ? FORK_CHAIN_ID : Number(j.chainId ?? /^(\d+)\.json$/.exec(f)?.[1])
    if (!Number.isInteger(chainId)) throw new Error(`${f}: no chainId`)
    const cpu = j.processor ?? j.cpu ?? j
    const circuits = cpu.circuits
    if (!isAddr(circuits)) throw new Error(`${f}: missing CPU circuits address`)
    const scope = [j.scope, j.cerebrScope, j.CerebrScope].find(isAddr)
    const block = Number(cpu.createBlock ?? cpu.block ?? cpu.deployBlock ?? j.deployBlock ?? 0) || undefined
    cpus[chainId] = {
      chainId,
      circuits,
      ...(isAddr(cpu.transistors) ? { transistors: cpu.transistors } : {}),
      ...(scope ? { scope } : {}),
      ...(block ? { block } : {}),
      catalog: catalogOf(j),
    }
    console.log(`cpu: chain ${chainId}${fork ? ' (fork)' : ''} circuits ${circuits}${scope ? ` scope ${scope}` : ''} (${f})`)
  }
} else {
  console.log(`no ${dir}: writing an empty config`)
}
mkdirSync(dirname(out), { recursive: true })
writeFileSync(
  out,
  `// AUTO-GENERATED by scripts/sync-cpu.mjs from launch/out/*.json. Do not edit.\n` +
    `import type { CpuConfig } from '${relative(dirname(out), join(appRoot, 'src/config/cpu.ts')).replace(/^(?!\.)/, './')}'\n\n` +
    `export const generatedCpus: Record<number, CpuConfig> = ${JSON.stringify(cpus, null, 2)}\n`,
)
console.log(`wrote ${out} (${Object.keys(cpus).length} chain(s))`)
